baseURL = "https://dlpeterson.com/"
languageCode = "en-us"
title = "Luke's Blog"
theme = "kiss"

copyright = "Luke Peterson, <a href=\"https://creativecommons.org/licenses/by/4.0/\">some rights reserved</a>."
Paginate = 10 # Number of posts per page
enableRobotsTXT = true
canonifyURLs = true
summaryLength = 30
enableEmoji = true

[permalinks]
posts = "/blog/:year/:month/:day/:title/"

[params]
author = "Luke Peterson"
description = "Luke Peterson's blog and personal website"

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "Luke Peterson"
authorEmail = "hazelnusse@gmail.com"

[params.assets]
# customCSS = ["css/custom.css"]

[params.info]
# adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = false # Adds powered by Hugo and Kiss below Copyright section
related = true # Includes related articles

[params.social]
twitter = "hazelnusse"
github = "hazelnusse"
email = "hazelnusse@gmail.com"
linkedin = "dalelukaspeterson"
rss = "posts/index.xml" # Add this to show RSS button in social.
# instagram = ""
# codepen = ""
# facebook = ""

[params.social.config]
platforms = [
    "rss",
    "email",
    "github",
    "twitter",
    "linkedin"
]

# [params.matomoAnalytics]
# siteID = 1
# rootURL = "//matomo.example.com/"
# 
# [params.fathomAnalytics]
# rootURL = "//fathom.example.com/"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

[imaging]
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
resampleFilter = "lanczos"

# Default JPEG quality setting. Default is 75.
quality = 97

# Anchor used when cropping pictures.
# Default is "smart" which does Smart Cropping, using https://github.com/muesli/smartcrop
# Smart Cropping is content aware and tries to find the best crop for each image.
# Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
anchor = "smart"
