#!/usr/bin/env python

import os
from sys import argv
import datetime

def initialize_file(filename):
    suffix = filename.split(".")[0]
    filename = os.path.abspath("content/posts") + "/" + filename
    if os.path.isfile(filename):
        raise FileExistsError(filename)

    d = datetime.datetime.utcnow()
    month = str(d.month)
    if len(month) == 1: month = "0" + month
    day = str(d.day)
    if len(day) == 1: day = "0" + day
    hr = str(d.hour)
    if len(hr) == 1: hr = "0" + hr
    min = str(d.minute)
    if len(min) == 1: min = "0" + min

    post_date = "{0}-{1}-{2} {3}:{4}".format(d.year, month, day, hr, min)
    initial_text = "date: " + post_date + "\n"
    initial_text += "title: {0}\n".format(suffix)
    initial_text += "tags: \n\n"
    f = open(filename, "w")
    f.write(initial_text)
    f.close()
    return filename

if len(argv) != 2:
    print("Supply a file name for the new post.")
elif os.environ['EDITOR'] == '/usr/bin/vim':
    filename = initialize_file(argv[1])
    os.system("vim +star \"+call cursor(2, 8)\" " + filename)
else:
    print("Get a real editor.")


